### ISSUE TITLE
Howto create a ruby app when there is no gem 

### ISSUE THREAD

**Issue by ngiger** [sagittaros/ruby-nix#4]
I am looking for a solution howto build https://github/zdavatz/migel where I have a gemfile, but the app is NOT published a gem.

**Comment by sagittaros** [comment]
The high level steps to build the environment of the gemfile are essentially:
1. ensure Gemfile.lock is in your path
2. run `bundix`
3. run `nix develop` to enter the shell

Let me know if I answered your question.
